### PR TITLE
Fix submodule & update paper numbers

### PR DESCRIPTION
**Pull request by h-vetinari**
You seem to not be having fun with submodules 😅 

So I hope this isn't presumptuous, but I thought I could open a PR that fixes it, now pointing to https://github.com/ThePhD/future_cxx/commit/8575bad3ad28478056f9fbb530fca84d5d41332a, and while I was at it, update the newest paper numbers.

### CODE REVIEW

**Comment by ThePhD** [comment]
How did you change the hash directly?

**Comment by h-vetinari** [comment]
> How did you change the hash directly?

Nuke `future_cxx` under `_vendor` and do a fresh `git clone`... 🙃 

(well, in my case the checkout of this repo didn't have the submodule populated yet, but it should work like that for you as well)

**Comment by h-vetinari** [comment]
> Nuke `future_cxx` under `_vendor` and do a fresh `git clone`... 🙃

Obviously, this will kill any non-pushed changes in your local checkout (if the submodule here is the reference version and the `.git` inside `future_cxx` gets deleted along with the folder). I'm sure there's less destructive ways too, but this worked really hassle-free at least.

**Comment by h-vetinari** [comment]
> I'm sure there's less destructive ways too, but this worked really hassle-free at least.

I'm thinking a `git reset --hard origin/main` within `future_cxx` should also do the trick, actually (and probably making sure there are no untracked files left).

**Pull request merged**
